// ============================================
// EmojiLang Code Generator
// ============================================
// Traverses the optimized AST and generates equivalent JavaScript code.

import { NodeType } from './parser.js';

/**
 * Code Generator class
 */
export class CodeGenerator {
  constructor() {
    this.indent = 0;
    this.output = '';
  }

  /**
   * Generate JavaScript from the AST
   * @param {Object} ast - The optimized AST
   * @returns {string} - Generated JavaScript code
   */
  generate(ast) {
    this.indent = 0;
    this.output = '';
    this.visitNode(ast);
    return this.output;
  }

  /**
   * Get current indentation string
   */
  getIndent() {
    return '  '.repeat(this.indent);
  }

  /**
   * Emit code
   */
  emit(code) {
    this.output += code;
  }

  /**
   * Emit a line of code with proper indentation
   */
  emitLine(code) {
    this.output += this.getIndent() + code + '\n';
  }

  /**
   * Visit an AST node and generate code
   */
  visitNode(node) {
    if (!node || !node.type) return '';

    switch (node.type) {
      case NodeType.PROGRAM:
        return this.visitProgram(node);
      case NodeType.VAR_DECLARATION:
        return this.visitVarDeclaration(node);
      case NodeType.ASSIGNMENT:
        return this.visitAssignment(node);
      case NodeType.PRINT:
        return this.visitPrint(node);
      case NodeType.INPUT:
        return this.visitInput(node);
      case NodeType.IF_STATEMENT:
        return this.visitIf(node);
      case NodeType.WHILE_LOOP:
        return this.visitWhile(node);
      case NodeType.FOR_LOOP:
        return this.visitFor(node);
      case NodeType.FUNC_DECLARATION:
        return this.visitFuncDeclaration(node);
      case NodeType.FUNC_CALL:
        return this.visitFuncCall(node);
      case NodeType.RETURN:
        return this.visitReturn(node);
      case NodeType.BLOCK:
        return this.visitBlock(node);
      case NodeType.BINARY_EXPR:
        return this.visitBinaryExpr(node);
      case NodeType.UNARY_EXPR:
        return this.visitUnaryExpr(node);
      case NodeType.NUMBER_LITERAL:
        return String(node.value);
      case NodeType.STRING_LITERAL:
        return this.visitStringLiteral(node);
      case NodeType.BOOL_LITERAL:
        return String(node.value);
      case NodeType.IDENTIFIER:
        return this.sanitizeIdentifier(node.name);
      case NodeType.ARRAY_LITERAL:
        return this.visitArrayLiteral(node);
      case NodeType.INDEX_ACCESS:
        return this.visitIndexAccess(node);
      default:
        return '';
    }
  }

  /**
   * Sanitize emoji identifier to valid JS identifier
   */
  sanitizeIdentifier(name) {
    // Convert emoji identifier to a safe JS variable name
    // Use a deterministic mapping
    let result = '_e';
    for (let i = 0; i < name.length; i++) {
      const cp = name.codePointAt(i);
      result += '_' + cp.toString(16);
      if (cp > 0xFFFF) i++; // Skip surrogate pair
    }
    return result;
  }

  visitProgram(node) {
    // Add runtime header comment
    this.emitLine('// Generated by EmojiLang Compiler');
    this.emitLine('// ================================\n');

    for (const stmt of node.body) {
      this.visitStatement(stmt);
    }
  }

  /**
   * Visit a statement node and emit it as a line
   */
  visitStatement(node) {
    if (!node) return;

    switch (node.type) {
      case NodeType.VAR_DECLARATION:
      case NodeType.ASSIGNMENT:
      case NodeType.PRINT:
      case NodeType.RETURN:
        this.emitLine(this.visitNode(node) + ';');
        break;
      case NodeType.IF_STATEMENT:
      case NodeType.WHILE_LOOP:
      case NodeType.FOR_LOOP:
      case NodeType.FUNC_DECLARATION:
        this.visitNode(node);
        break;
      case NodeType.BLOCK:
        this.visitBlock(node);
        break;
      case NodeType.FUNC_CALL:
        this.emitLine(this.visitNode(node) + ';');
        break;
      default:
        // Expression statement
        const expr = this.visitNode(node);
        if (expr) {
          this.emitLine(expr + ';');
        }
    }
  }

  visitVarDeclaration(node) {
    const name = this.sanitizeIdentifier(node.name);
    const init = this.visitNode(node.init);
    return `let ${name} = ${init}`;
  }

  visitAssignment(node) {
    const target = this.visitNode(node.target);
    const value = this.visitNode(node.value);
    return `${target} = ${value}`;
  }

  visitPrint(node) {
    const arg = this.visitNode(node.arg);
    return `console.log(${arg})`;
  }

  visitInput(node) {
    if (node.prompt) {
      const prompt = this.visitNode(node.prompt);
      return `prompt(${prompt})`;
    }
    return `prompt("")`;
  }

  visitIf(node) {
    const condition = this.visitNode(node.condition);
    this.emitLine(`if (${condition}) {`);
    this.indent++;

    // Visit consequent block body directly
    if (node.consequent.type === NodeType.BLOCK) {
      for (const stmt of node.consequent.body) {
        this.visitStatement(stmt);
      }
    } else {
      this.visitStatement(node.consequent);
    }

    this.indent--;

    if (node.alternate) {
      if (node.alternate.type === NodeType.IF_STATEMENT) {
        this.emit(this.getIndent() + '} else ');
        this.visitNode(node.alternate);
      } else {
        this.emitLine('} else {');
        this.indent++;
        if (node.alternate.type === NodeType.BLOCK) {
          for (const stmt of node.alternate.body) {
            this.visitStatement(stmt);
          }
        } else {
          this.visitStatement(node.alternate);
        }
        this.indent--;
        this.emitLine('}');
      }
    } else {
      this.emitLine('}');
    }

    return '';
  }

  visitWhile(node) {
    const condition = this.visitNode(node.condition);
    this.emitLine(`while (${condition}) {`);
    this.indent++;

    if (node.body.type === NodeType.BLOCK) {
      for (const stmt of node.body.body) {
        this.visitStatement(stmt);
      }
    } else {
      this.visitStatement(node.body);
    }

    this.indent--;
    this.emitLine('}');

    return '';
  }

  visitFor(node) {
    const init = node.init ? this.visitNode(node.init) : '';
    const condition = node.condition ? this.visitNode(node.condition) : '';
    const update = node.update ? this.visitNode(node.update) : '';

    this.emitLine(`for (${init}; ${condition}; ${update}) {`);
    this.indent++;

    if (node.body.type === NodeType.BLOCK) {
      for (const stmt of node.body.body) {
        this.visitStatement(stmt);
      }
    } else {
      this.visitStatement(node.body);
    }

    this.indent--;
    this.emitLine('}');

    return '';
  }

  visitFuncDeclaration(node) {
    const name = this.sanitizeIdentifier(node.name);
    const params = node.params.map(p => this.sanitizeIdentifier(p)).join(', ');

    this.emitLine(`function ${name}(${params}) {`);
    this.indent++;

    if (node.body.type === NodeType.BLOCK) {
      for (const stmt of node.body.body) {
        this.visitStatement(stmt);
      }
    } else {
      this.visitStatement(node.body);
    }

    this.indent--;
    this.emitLine('}');
    this.emit('\n');

    return '';
  }

  visitFuncCall(node) {
    const callee = this.sanitizeIdentifier(node.callee);
    const args = node.args.map(a => this.visitNode(a)).join(', ');
    return `${callee}(${args})`;
  }

  visitReturn(node) {
    if (node.value) {
      const value = this.visitNode(node.value);
      return `return ${value}`;
    }
    return 'return';
  }

  visitBlock(node) {
    for (const stmt of node.body) {
      this.visitStatement(stmt);
    }
    return '';
  }

  visitBinaryExpr(node) {
    const left = this.visitNode(node.left);
    const right = this.visitNode(node.right);
    return `(${left} ${node.op} ${right})`;
  }

  visitUnaryExpr(node) {
    const operand = this.visitNode(node.operand);
    return `(${node.op}${operand})`;
  }

  visitStringLiteral(node) {
    // Escape special characters
    const escaped = node.value
      .replace(/\\/g, '\\\\')
      .replace(/"/g, '\\"')
      .replace(/\n/g, '\\n')
      .replace(/\r/g, '\\r')
      .replace(/\t/g, '\\t');
    return `"${escaped}"`;
  }

  visitArrayLiteral(node) {
    const elements = node.elements.map(e => this.visitNode(e)).join(', ');
    return `[${elements}]`;
  }

  visitIndexAccess(node) {
    const obj = this.visitNode(node.object);
    const index = this.visitNode(node.index);
    return `${obj}[${index}]`;
  }
}

/**
 * Add syntax highlighting spans to generated JS code
 */
export function highlightJS(code) {
  // First escape HTML to prevent injection
  const escMap = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' };
  let result = code.replace(/[&<>"']/g, c => escMap[c]);

  // Apply syntax highlighting with spans
  const comments = /(\/\/.*$)/gm;
  const strings = /(&quot;(?:[^&]|&(?!quot;))*?&quot;|&#039;(?:[^&]|&(?!#039;))*?&#039;)/g;
  const keywords = /\b(let|const|var|function|return|if|else|while|for|true|false|null|undefined|new|typeof|instanceof)\b/g;
  const numbers = /\b(\d+\.?\d*)\b/g;

  result = result.replace(comments, '<span class="cm">$1</span>');
  result = result.replace(strings, '<span class="str">$1</span>');
  result = result.replace(keywords, '<span class="kw">$1</span>');
  result = result.replace(numbers, '<span class="num">$1</span>');

  return result;
}
